webAdventure/game/urls.py
from django.urls import path
from . import views

# paths for the urls

app_name = "main"
urlpatterns = [
    path("", views.title),
    # you have to put world in the url, but this can be changed
    # when you click start, which should do that
    path("world", views.world, name='world'),
    path("battle", views.battle, name='battle')
]

webAdventure/webAdventure/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
]

webAdventure/game/models.py
from django.db import models

# Create your models here.

webAdventure/game/views.py
from django.shortcuts import render

import random
from django import forms

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse  # i think these are not needed
from django.template import loader  # i think these are not needed

# there will be images with same format in the visual value
# more dictionary values will be added
# 49 more...
welcome = [
    {'visual': "img-6-3", 'title': "Starting out", 'description': "Here is a long description for the page",
        'yousee': ['stick', 'map', 'potion']
     },
    {
        'visual': "img-6-2", 'title': "The Wrestling room", 'description': "I DON'T WANT TO TYPE ANYMORE", 'yousee': ['sword', 'chair', 'enemy']
    },
    {
        'visual': "img-6-1", 'title': "The Room", 'description': "A strange futuristic vibe fills the room", 'yousee': ['monitor', 'table', 'computer']
    },
    {
        'visual': "img-enemy", 'title': "An enemy approaches", 'description': "You find it astonishing that there are still monsterous beasts roaming the lands", 'yousee': ["enemy"]
    },
    {
        'visual': "img-key", 'title': "An objects shines", 'description': "you traverse the maladroit path and see something catch your eye", 'yousee': ["key"]
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
    {
        'visual': "", 'title': "", 'description': "", 'yousee': ""
    },
]


class NewTaskForm(forms.Form):
    terminal = forms.CharField(label=">")

    def clean_terminal(self):
        data = self.clean_terminal["terminal"]
        return data


# This will show the title.html page
def title(request):
    return render(request, "game/title.html")


def world(request):
    # This should be checked
    # welcome[changeMeDependingOnPosition][0]
    # welcome[changeMeDependingOnPosition][1]
    # welcome[changeMeDependingOnPosition][2]
    visual = welcome[4]['visual']
    title = welcome[4]['title']
    description = welcome[4]['description']
    yousee = welcome[4]['yousee']

# These are the variables that are sent to the html document
    context = {
        "visual": visual,
        "title": title,
        "description": description,
        "yousee": yousee,
        "terminal": NewTaskForm(),
    }
    return render(request, "game/world.html", context)


def battle(request):
    # button stuff for the gifs
    roll = 'false'
    rolled = random
    context = {
        "roll": roll
    }
    return render(request, 'game/battle.html')

webAdventure/game/templates/game/battle.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Battle</title>
    <!-- <link rel="stylesheet" href="{% static 'game/css/title.css' %}" /> -->
  </head>
  <body>
    <!-- This will show the image using the image name -->
    {% if roll == true %}
        {% with 'game/images/'|add:rolled|add:'.png' as image_static %}
        <img src="{% static image_static %}" />
        {% endwith %}
    {% else %}
        <img src="{% static 'game/images/shaking.gif' %}">
    {% endif %}
  </body>
</html>

webAdventure/game/templates/game/title.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>WebGame-Sample</title>
    <link rel="stylesheet" href="{% static 'game/css/style.css' %}" />
  </head>
  <body>
    <div class="page-outer">
      <section class="section-full">
        <div class="container image">
          <img src="{% static 'game/images/titleSample.png' %}" />
        </div>
        <h1>This is the title thing</h1>
        <div class="container text">
            <p>Something brief like press something to enter/start</p>
            <aside>
              <p><br />Everything will be centered and styled stuff</p>
            </aside>
          </div>
          <!-- do something with this button so it send world in the url to move on -->
          <div class="btn">
              <a href="{% url 'main:world' %}">
                <p>start</p>
              </a>
          </div>
      </section>
  </div>
  </body>
</html>

webAdventure/game/templates/game/world.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>WebGame-Sample</title>
    <link rel="stylesheet" href="{% static 'game/css/style.css' %}" />
  </head>
  <body>
    <div class="page-outer">

      <section class="section-full">
        <div class="container image">
          {% comment %} This will show the image using the image name {% endcomment %}
          {% with 'game/images/'|add:visual|add:'.png' as image_static %}
          <img src="{% static image_static %}" />
          {% endwith %}
        </div>

        {% comment %} Printing the title and description {% endcomment %}
        <h1>{{ title }}</h1>

        <div class="container text">
          <p>{{ description }}</p>
        </div>
        {% comment %} the markup below will print the items {% endcomment %}

        <ul>
          {% for item in yousee %}
          <li>{{ item }}</li>
          {% endfor %}
        </ul>

        <!-- <form action = "" method = "post">
          {% csrf_token %}
          <label for="your_name">Your name: </label>
          <input id="your_name" type="text" name="your_name">
          <input type="submit" value="OK">
        </form> -->

        <div class=" choice btn">
          <a href="{% url 'main:world' %}">Start</a>
          <a href="{% url 'main:world' %}">Startt</a>
          <a href="{% url 'main:world' %}">Startttt</a>
          <a href="{% url 'main:world' %}">Starttttt</a>
        </btn>

<!-- 
      {% if o == north %}
      <p>north</p>
      {%else%}
      <p>nothing</p>
      {%endif%} -->
    </section>
    {{ direction }}
    </div>
  </body>
</html>